unit TestUProduto;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UProduto;

type
  // Test methods for class TProduto

  TestTProduto = class(TTestCase)
  strict private
    FProduto: TProduto;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestRetornarValorTotal;
  end;

implementation

procedure TestTProduto.SetUp;
begin
  FProduto := TProduto.Create;
  FProduto.Preco_Unitario := 100;
end;

procedure TestTProduto.TearDown;
begin
  FProduto.Free;
  FProduto := nil;
end;

procedure TestTProduto.TestRetornarValorTotal;
var
  ReturnValue: Currency;
begin
  FProduto.Quantidade := 10;
  ReturnValue := FProduto.RetornarValorTotal;
  CheckEquals(1000, ReturnValue, 'Erro no retornar valor');

   FProduto.Quantidade := 20;
  ReturnValue := FProduto.RetornarValorTotal;
  CheckEquals(1800, ReturnValue, 'Erro no retornar valor com 10% desconto');

  FProduto.Quantidade := 60;
  ReturnValue := FProduto.RetornarValorTotal;
  CheckEquals(4500, ReturnValue, 'Erro no retornar valor com 10% desconto');
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTProduto.Suite);
end.

